/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import control.AccountControl;

/**
 *
 * @author Raphael
 */
public class AccountDialog extends javax.swing.JDialog
{
    private AccountControl ac;
    /**
     * Creates new form AccountDialog
     */
    public AccountDialog(AccountControl ac)
    {        
        initComponents();
        this.ac = ac;
        setSize(400,300);
        setModal(true);
        setModalityType(ModalityType.APPLICATION_MODAL);
        setAlwaysOnTop(true);
        setTitle("Your Account");
        initData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbType = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbMatNumber = new javax.swing.JLabel();
        btTeacherRequest = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel1.setText("Name");
        jPanel1.add(jLabel1);

        lbName.setText("                        ");
        jPanel1.add(lbName);

        jLabel2.setText("Account type");
        jPanel1.add(jLabel2);

        lbType.setText("            ");
        jPanel1.add(lbType);

        jLabel4.setText("Matriculation number");
        jPanel1.add(jLabel4);

        lbMatNumber.setText("                 ");
        jPanel1.add(lbMatNumber);

        btTeacherRequest.setText("Request teacher privileges");
        btTeacherRequest.setMargin(new java.awt.Insets(5, 14, 5, 14));
        btTeacherRequest.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btTeacherRequestActionPerformed(evt);
            }
        });
        jPanel1.add(btTeacherRequest);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btTeacherRequestActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btTeacherRequestActionPerformed
    {//GEN-HEADEREND:event_btTeacherRequestActionPerformed
        ac.requestTeacherPrivileges();
        btTeacherRequest.setEnabled(false);
        btTeacherRequest.setText("Teacher privileges requested");
    }//GEN-LAST:event_btTeacherRequestActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btTeacherRequest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbMatNumber;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbType;
    // End of variables declaration//GEN-END:variables

    private void initData()
    {
        lbName.setText(ac.getUserName());
        lbMatNumber.setText(""+ac.getUserMatNumber());
        lbType.setText(ac.getUserType().toString());
        if(!ac.canUserRequestTeacherPrivileges())
        {
            btTeacherRequest.setEnabled(false);
            btTeacherRequest.setText("Teacher privileges requested");
        }
    }
}
