/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import control.CourseControl;
import model.user.UserGroupListModel;

/**
 *
 * @author Raphael
 */
public class CourseAddDialog extends javax.swing.JDialog
{
    private CourseControl cc;
    /**
     * Creates new form CourseAddDialog
     */
    public CourseAddDialog(CourseControl cc,UserGroupListModel teachersCourseLM, UserGroupListModel teachersLM)
    {
        initComponents();
        this.cc = cc;
        teacherList.setModel(teachersLM);
        courseTeacherList.setModel(teachersCourseLM);
        setSize(600,300);
        setModal(true);
        setModalityType(ModalityType.APPLICATION_MODAL);
        setAlwaysOnTop(true);
        setTitle("Add Course");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        tfId = new javax.swing.JTextField();
        tfName = new javax.swing.JTextField();
        spSemesterHours = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        teacherList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        courseTeacherList = new javax.swing.JList();
        jPanel6 = new javax.swing.JPanel();
        btAddTeacher = new javax.swing.JButton();
        btRemoveTeacher = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btAddCourse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 300));
        setPreferredSize(new java.awt.Dimension(600, 363));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel4.setLayout(new java.awt.GridLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Course details"));
        jPanel1.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(tfId, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(tfName, gridBagConstraints);

        spSemesterHours.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.5f), Float.valueOf(0.5f), null, Float.valueOf(0.5f)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 0);
        jPanel1.add(spSemesterHours, gridBagConstraints);

        jLabel1.setText("Course ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Semester hours");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        jPanel1.add(jLabel3, gridBagConstraints);

        jPanel4.add(jPanel1);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        teacherList.setBorder(javax.swing.BorderFactory.createTitledBorder("All teachers"));
        teacherList.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(teacherList);

        jPanel2.add(jScrollPane1);

        courseTeacherList.setBorder(javax.swing.BorderFactory.createTitledBorder("Selected Teachers"));
        courseTeacherList.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(courseTeacherList);

        jPanel2.add(jScrollPane2);

        jPanel3.add(jPanel2);

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        btAddTeacher.setText("Add Teacher");
        btAddTeacher.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btAddTeacherActionPerformed(evt);
            }
        });
        jPanel6.add(btAddTeacher);

        btRemoveTeacher.setText("Remove Teacher");
        btRemoveTeacher.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btRemoveTeacherActionPerformed(evt);
            }
        });
        jPanel6.add(btRemoveTeacher);

        jPanel3.add(jPanel6);

        jPanel4.add(jPanel3);

        getContentPane().add(jPanel4);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        btAddCourse.setText("Add Course");
        btAddCourse.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btAddCourse.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btAddCourseActionPerformed(evt);
            }
        });
        jPanel5.add(btAddCourse);

        getContentPane().add(jPanel5);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAddTeacherActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btAddTeacherActionPerformed
    {//GEN-HEADEREND:event_btAddTeacherActionPerformed
        cc.addTeacherToCourseList(teacherList.getSelectedIndex());
    }//GEN-LAST:event_btAddTeacherActionPerformed

    private void btRemoveTeacherActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btRemoveTeacherActionPerformed
    {//GEN-HEADEREND:event_btRemoveTeacherActionPerformed
        cc.removeTeacherFromCourseList(courseTeacherList.getSelectedIndex());
    }//GEN-LAST:event_btRemoveTeacherActionPerformed

    private void btAddCourseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btAddCourseActionPerformed
    {//GEN-HEADEREND:event_btAddCourseActionPerformed
        cc.addCourse(tfId.getText(), tfName.getText(), (float)spSemesterHours.getValue());
        dispose();
    }//GEN-LAST:event_btAddCourseActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddCourse;
    private javax.swing.JButton btAddTeacher;
    private javax.swing.JButton btRemoveTeacher;
    private javax.swing.JList courseTeacherList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner spSemesterHours;
    private javax.swing.JList teacherList;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables
}
