/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import control.MainControl;
import model.user.UserType;

/**
 *
 * @author Raphael
 */
public class MainView extends javax.swing.JFrame
{
    private MainControl mc;
    /**
     * Creates new form MainView
     * @param mc
     */
    public MainView(MainControl mc)
    {
        initComponents();
        btUsers.setEnabled(false);
        this.mc = mc;
        setSize(400,300);
        initForUsergroup();
    }   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        mainPanel = new javax.swing.JPanel();
        btUsers = new javax.swing.JButton();
        btCourses = new javax.swing.JButton();
        btTimetable = new javax.swing.JButton();
        btAccount = new javax.swing.JButton();
        btCurricula = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        mainPanel.setLayout(new java.awt.GridLayout(2, 2));

        btUsers.setText("Users");
        btUsers.setMaximumSize(new java.awt.Dimension(1000, 1000));
        btUsers.setMinimumSize(new java.awt.Dimension(300, 300));
        btUsers.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btUsersActionPerformed(evt);
            }
        });
        mainPanel.add(btUsers);

        btCourses.setText("Courses");
        btCourses.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btCoursesActionPerformed(evt);
            }
        });
        mainPanel.add(btCourses);

        btTimetable.setText("Time table");
        mainPanel.add(btTimetable);

        btAccount.setText("My account");
        btAccount.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btAccountActionPerformed(evt);
            }
        });
        mainPanel.add(btAccount);

        btCurricula.setText("Curricula");
        btCurricula.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btCurriculaActionPerformed(evt);
            }
        });
        mainPanel.add(btCurricula);

        getContentPane().add(mainPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCurriculaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btCurriculaActionPerformed
    {//GEN-HEADEREND:event_btCurriculaActionPerformed
        mc.displayCurriculum();
    }//GEN-LAST:event_btCurriculaActionPerformed

    private void btCoursesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btCoursesActionPerformed
    {//GEN-HEADEREND:event_btCoursesActionPerformed
        mc.displayCourses();
    }//GEN-LAST:event_btCoursesActionPerformed

    private void btAccountActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btAccountActionPerformed
    {//GEN-HEADEREND:event_btAccountActionPerformed
        mc.displayAccount();
    }//GEN-LAST:event_btAccountActionPerformed

    private void btUsersActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btUsersActionPerformed
    {//GEN-HEADEREND:event_btUsersActionPerformed
        mc.displayUserDialog();
    }//GEN-LAST:event_btUsersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAccount;
    private javax.swing.JButton btCourses;
    private javax.swing.JButton btCurricula;
    private javax.swing.JButton btTimetable;
    private javax.swing.JButton btUsers;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables

    private void initForUsergroup()
    {
        if(mc.getUserType() == UserType.ADMIN)
        {
            btUsers.setEnabled(true);
        }
    }
}
