/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import control.UserControl;

/**
 *
 * @author Raphael
 */
public class UserRequestDialog extends javax.swing.JDialog
{
    private UserControl uc;
    /**
     * Creates new form UserRequestDialog
     */
    public UserRequestDialog(UserControl uc)
    {
        initComponents();
        this.uc = uc;
        
        list.setModel(uc.getTeacherRequestListModel());
        
        setSize(400,300);
        setModal(true);
        setModalityType(ModalityType.APPLICATION_MODAL);
        setAlwaysOnTop(true);
        setTitle("Grant teacher privileges");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        btRefuse = new javax.swing.JButton();
        btGrant = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        list.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        list.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jScrollPane1.setViewportView(list);

        jPanel1.add(jScrollPane1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        btRefuse.setText("Refuse");
        btRefuse.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btRefuseActionPerformed(evt);
            }
        });
        jPanel2.add(btRefuse);

        btGrant.setText("Grant");
        btGrant.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btGrantActionPerformed(evt);
            }
        });
        jPanel2.add(btGrant);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRefuseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btRefuseActionPerformed
    {//GEN-HEADEREND:event_btRefuseActionPerformed
        uc.setTeacherPrivileges(list.getSelectedIndex(), false);
    }//GEN-LAST:event_btRefuseActionPerformed

    private void btGrantActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btGrantActionPerformed
    {//GEN-HEADEREND:event_btGrantActionPerformed
        uc.setTeacherPrivileges(list.getSelectedIndex(), true);
    }//GEN-LAST:event_btGrantActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGrant;
    private javax.swing.JButton btRefuse;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList list;
    // End of variables declaration//GEN-END:variables
}
